name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: checklist-offline

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies
        run: npm install

      - name: Gerar ícones do app
        run: npx capacitor-assets generate --android

      - name: Install Capacitor
        run: npm install @capacitor/android @capacitor/core @capacitor/cli

      - name: Init Capacitor
        run: |
          if [ ! -d android ]; then
            npx cap add android
          fi

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: checklist-agt-apk
          path: checklist-offline/android/app/build/outputs/apk/debug/app-debug.apk
