name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Descobrir pasta do app
        run: |
          if [ -f package.json ]; then
            echo "APP_DIR=." >> $GITHUB_ENV
          elif [ -f checklist-offline/package.json ]; then
            echo "APP_DIR=checklist-offline" >> $GITHUB_ENV
          else
            echo "package.json não encontrado"
            exit 1
          fi

      - name: Instalar dependências
        run: |
          cd "$APP_DIR"
          npm install

      - name: Criar Android
        run: |
          cd "$APP_DIR"
          npx cap add android

      - name: Sincronizar Capacitor
        run: |
          cd "$APP_DIR"
          npx cap sync android

      - name: Gerar APK
        run: |
          cd "$APP_DIR/android"
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: checklist-agt-apk
          path: ${{ env.APP_DIR }}/android/app/build/outputs/apk/debug/app-debug.apk
